mainWorld: world
#main world
seed: 12345
#seed for world generator plugin
enabled: false
# After setting the config, you can replace it with "true"
useMultiverseCore: false
# Does your server use the MultiverseCore plugin?
defaultWorldBorderDistance: 1000
# Default world board distance
fuelItems:
  - brown_mushroom
  - red_mushroom
  - melon
  - carved_pumpkin
  - pumpkin
  - crimson_fungus
  - warped_fungus
  - popped_chorus_fruit
  - cooked_beef
  - cooked_chicken
  - cooked_cod
  - cooked_mutton
  - cooked_porkchop
  - cooked_rabbit
  - cooked_salmon
  - ink_sac
  - glow_ink_sac

worlds_with_meteors:
  world:
    minExplosionPower: 1.0
    maxExplosionPower: 3.0
    minSpawnDelay: 864000
    maxSpawnDelay: 1728000
    types:
      - titanium
      - lithium
      - nasturan
      - meteoric_iron