enabled: false
# After setting the config, you can replace it with "true"
useMultiverseCore: false
# Does your server use the MultiverseCore plugin?
fuelItems:
  - brown_mushroom
  - red_mushroom
  - melon
  - carved_pumpkin
  - pumpkin
  - crimson_fungus
  - warped_fungus
  - popped_chorus_fruit
  - cooked_beef
  - cooked_chicken
  - cooked_cod
  - cooked_mutton
  - cooked_porkchop
  - cooked_rabbit
  - cooked_salmon